var TREE_ITEMS = [
['TOP', './index.html', ['DataBases', 'DataBases/index.html', ['BDDConnection', 'DataBases/BDDConnection/index.html', ['Abstracts', 'DataBases/BDDConnection/Abstracts/index.html']
, ['Errors', 'DataBases/BDDConnection/Errors/index.html', ['BDDError.php', 'DataBases/BDDConnection/Errors/BDDError.php.html']
]
, ['Interfaces', 'DataBases/BDDConnection/Interfaces/index.html', ['BDDConnectionInterface.php', 'DataBases/BDDConnection/Interfaces/BDDConnectionInterface.php.html']
, ['BDDTableInterface.php', 'DataBases/BDDConnection/Interfaces/BDDTableInterface.php.html']
]
, ['Iterators', 'DataBases/BDDConnection/Iterators/index.html', ['BDDRecord.php', 'DataBases/BDDConnection/Iterators/BDDRecord.php.html']
, ['BDDRecordSet.php', 'DataBases/BDDConnection/Iterators/BDDRecordSet.php.html']
]
, ['BDDConnection.php', 'DataBases/BDDConnection/BDDConnection.php.html']
, ['BDDTable.php', 'DataBases/BDDConnection/BDDTable.php.html']
, ['loader.php', 'DataBases/BDDConnection/loader.php.html']
]
, ['MySQLConnection', 'DataBases/MySQLConnection/index.html', ['Abstracts', 'DataBases/MySQLConnection/Abstracts/index.html']
, ['Errors', 'DataBases/MySQLConnection/Errors/index.html']
, ['Interfaces', 'DataBases/MySQLConnection/Interfaces/index.html']
, ['Iterators', 'DataBases/MySQLConnection/Iterators/index.html']
, ['MySQLConnection.php', 'DataBases/MySQLConnection/MySQLConnection.php.html']
, ['MySQLTable.php', 'DataBases/MySQLConnection/MySQLTable.php.html']
, ['loader.php', 'DataBases/MySQLConnection/loader.php.html']
]
, ['loader.php', 'DataBases/loader.php.html']
]
, ['Exetron', 'Exetron/index.html', ['TableGroup', 'Exetron/TableGroup/index.html', ['Abstracts', 'Exetron/TableGroup/Abstracts/index.html']
, ['Errors', 'Exetron/TableGroup/Errors/index.html', ['GroupError.php', 'Exetron/TableGroup/Errors/GroupError.php.html']
]
, ['Interfaces', 'Exetron/TableGroup/Interfaces/index.html', ['TableGroupInterface.php', 'Exetron/TableGroup/Interfaces/TableGroupInterface.php.html']
]
, ['Iterators', 'Exetron/TableGroup/Iterators/index.html', ['Group.php', 'Exetron/TableGroup/Iterators/Group.php.html']
, ['Groups.php', 'Exetron/TableGroup/Iterators/Groups.php.html']
]
, ['MySQLTableGroup.php', 'Exetron/TableGroup/MySQLTableGroup.php.html']
, ['TableGroup.php', 'Exetron/TableGroup/TableGroup.php.html']
, ['loader.php', 'Exetron/TableGroup/loader.php.html']
]
, ['TableSite', 'Exetron/TableSite/index.html', ['Abstracts', 'Exetron/TableSite/Abstracts/index.html']
, ['Errors', 'Exetron/TableSite/Errors/index.html', ['SiteError.php', 'Exetron/TableSite/Errors/SiteError.php.html']
]
, ['Interfaces', 'Exetron/TableSite/Interfaces/index.html', ['TableSiteInterface.php', 'Exetron/TableSite/Interfaces/TableSiteInterface.php.html']
]
, ['Iterators', 'Exetron/TableSite/Iterators/index.html', ['Site.php', 'Exetron/TableSite/Iterators/Site.php.html']
, ['Sites.php', 'Exetron/TableSite/Iterators/Sites.php.html']
]
, ['MySQLTableSite.php', 'Exetron/TableSite/MySQLTableSite.php.html']
, ['TableSite.php', 'Exetron/TableSite/TableSite.php.html']
, ['loader.php', 'Exetron/TableSite/loader.php.html']
]
, ['TableUser', 'Exetron/TableUser/index.html', ['Abstracts', 'Exetron/TableUser/Abstracts/index.html']
, ['Errors', 'Exetron/TableUser/Errors/index.html', ['UserError.php', 'Exetron/TableUser/Errors/UserError.php.html']
]
, ['Interfaces', 'Exetron/TableUser/Interfaces/index.html', ['TableUserInterface.php', 'Exetron/TableUser/Interfaces/TableUserInterface.php.html']
]
, ['Iterators', 'Exetron/TableUser/Iterators/index.html', ['User.php', 'Exetron/TableUser/Iterators/User.php.html']
, ['Users.php', 'Exetron/TableUser/Iterators/Users.php.html']
]
, ['MySQLTableUser.php', 'Exetron/TableUser/MySQLTableUser.php.html']
, ['TableUser.php', 'Exetron/TableUser/TableUser.php.html']
, ['loader.php', 'Exetron/TableUser/loader.php.html']
]
, ['TableVariable', 'Exetron/TableVariable/index.html', ['Abstracts', 'Exetron/TableVariable/Abstracts/index.html']
, ['Errors', 'Exetron/TableVariable/Errors/index.html', ['VariableError.php', 'Exetron/TableVariable/Errors/VariableError.php.html']
]
, ['Interfaces', 'Exetron/TableVariable/Interfaces/index.html', ['TableVariableInterface.php', 'Exetron/TableVariable/Interfaces/TableVariableInterface.php.html']
]
, ['Iterators', 'Exetron/TableVariable/Iterators/index.html', ['Variable.php', 'Exetron/TableVariable/Iterators/Variable.php.html']
, ['Variables.php', 'Exetron/TableVariable/Iterators/Variables.php.html']
]
, ['MySQLTableVariable.php', 'Exetron/TableVariable/MySQLTableVariable.php.html']
, ['TableVariable.php', 'Exetron/TableVariable/TableVariable.php.html']
, ['loader.php', 'Exetron/TableVariable/loader.php.html']
]
, ['WebSitePage', 'Exetron/WebSitePage/index.html', ['Abstracts', 'Exetron/WebSitePage/Abstracts/index.html']
, ['Errors', 'Exetron/WebSitePage/Errors/index.html']
, ['Interfaces', 'Exetron/WebSitePage/Interfaces/index.html']
, ['Iterators', 'Exetron/WebSitePage/Iterators/index.html']
, ['WebSitePage.php', 'Exetron/WebSitePage/WebSitePage.php.html']
, ['loader.php', 'Exetron/WebSitePage/loader.php.html']
]
, ['XHTMLSitePage', 'Exetron/XHTMLSitePage/index.html', ['Abstracts', 'Exetron/XHTMLSitePage/Abstracts/index.html']
, ['Errors', 'Exetron/XHTMLSitePage/Errors/index.html']
, ['Interfaces', 'Exetron/XHTMLSitePage/Interfaces/index.html']
, ['Iterators', 'Exetron/XHTMLSitePage/Iterators/index.html']
, ['XHTMLSitePage.php', 'Exetron/XHTMLSitePage/XHTMLSitePage.php.html']
, ['loader.php', 'Exetron/XHTMLSitePage/loader.php.html']
]
, ['loader.php', 'Exetron/loader.php.html']
]
, ['System', 'System/index.html', ['AbstractClass', 'System/AbstractClass/index.html', ['Abstracts', 'System/AbstractClass/Abstracts/index.html']
, ['Errors', 'System/AbstractClass/Errors/index.html']
, ['Interfaces', 'System/AbstractClass/Interfaces/index.html', ['AbstractIterator.php', 'System/AbstractClass/Interfaces/AbstractIterator.php.html']
]
, ['Iterators', 'System/AbstractClass/Iterators/index.html']
, ['AbstractClass.php', 'System/AbstractClass/AbstractClass.php.html']
, ['loader.php', 'System/AbstractClass/loader.php.html']
]
, ['AbstractSingleton', 'System/AbstractSingleton/index.html', ['Abstracts', 'System/AbstractSingleton/Abstracts/index.html']
, ['Errors', 'System/AbstractSingleton/Errors/index.html']
, ['Interfaces', 'System/AbstractSingleton/Interfaces/index.html']
, ['Iterators', 'System/AbstractSingleton/Iterators/index.html']
, ['AbstractSingleton.php', 'System/AbstractSingleton/AbstractSingleton.php.html']
, ['loader.php', 'System/AbstractSingleton/loader.php.html']
]
, ['AbstractSitePage', 'System/AbstractSitePage/index.html', ['Abstracts', 'System/AbstractSitePage/Abstracts/index.html']
, ['Errors', 'System/AbstractSitePage/Errors/index.html', ['AbstractSitePageError.php', 'System/AbstractSitePage/Errors/AbstractSitePageError.php.html']
]
, ['Interfaces', 'System/AbstractSitePage/Interfaces/index.html']
, ['Iterators', 'System/AbstractSitePage/Iterators/index.html']
, ['AbstractSitePage.php', 'System/AbstractSitePage/AbstractSitePage.php.html']
, ['loader.php', 'System/AbstractSitePage/loader.php.html']
]
, ['Application', 'System/Application/index.html', ['Abstracts', 'System/Application/Abstracts/index.html']
, ['Errors', 'System/Application/Errors/index.html', ['ApplicationError.php', 'System/Application/Errors/ApplicationError.php.html']
]
, ['Interfaces', 'System/Application/Interfaces/index.html']
, ['Iterators', 'System/Application/Iterators/index.html']
, ['Application.php', 'System/Application/Application.php.html']
, ['loader.php', 'System/Application/loader.php.html']
]
, ['Errors', 'System/Errors/index.html', ['Abstracts', 'System/Errors/Abstracts/index.html']
, ['Errors', 'System/Errors/Errors/index.html', ['Error.php', 'System/Errors/Errors/Error.php.html']
]
, ['Interfaces', 'System/Errors/Interfaces/index.html']
, ['Iterators', 'System/Errors/Iterators/index.html']
, ['Errors.php', 'System/Errors/Errors.php.html']
, ['loader.php', 'System/Errors/loader.php.html']
]
, ['Session', 'System/Session/index.html', ['Abstracts', 'System/Session/Abstracts/index.html']
, ['Errors', 'System/Session/Errors/index.html', ['SessionError.php', 'System/Session/Errors/SessionError.php.html']
]
, ['Interfaces', 'System/Session/Interfaces/index.html', ['SessionInterface.php', 'System/Session/Interfaces/SessionInterface.php.html']
]
, ['Iterators', 'System/Session/Iterators/index.html']
, ['Session.php', 'System/Session/Session.php.html']
, ['loader.php', 'System/Session/loader.php.html']
]
, ['WebApplication', 'System/WebApplication/index.html', ['Abstracts', 'System/WebApplication/Abstracts/index.html']
, ['Errors', 'System/WebApplication/Errors/index.html']
, ['Interfaces', 'System/WebApplication/Interfaces/index.html']
, ['Iterators', 'System/WebApplication/Iterators/index.html']
, ['WebApplication.php', 'System/WebApplication/WebApplication.php.html']
, ['loader.php', 'System/WebApplication/loader.php.html']
]
, ['loader.php', 'System/loader.php.html']
]
, ['Templates', 'Templates/index.html', ['Template', 'Templates/Template/index.html', ['Abstracts', 'Templates/Template/Abstracts/index.html']
, ['Errors', 'Templates/Template/Errors/index.html', ['TemplateError.php', 'Templates/Template/Errors/TemplateError.php.html']
]
, ['Interfaces', 'Templates/Template/Interfaces/index.html']
, ['Iterators', 'Templates/Template/Iterators/index.html']
, ['Template.php', 'Templates/Template/Template.php.html']
, ['loader.php', 'Templates/Template/loader.php.html']
]
, ['XHTMLTemplates', 'Templates/XHTMLTemplates/index.html', ['XHTMLBodyTemplate', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/index.html', ['Abstracts', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/Abstracts/index.html']
, ['Errors', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/Errors/index.html']
, ['Interfaces', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/Interfaces/index.html']
, ['Iterators', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/Iterators/index.html']
, ['XHTMLBodyTemplate.php', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/XHTMLBodyTemplate.php.html']
, ['loader.php', 'Templates/XHTMLTemplates/XHTMLBodyTemplate/loader.php.html']
]
, ['XHTMLHeadersTemplate', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/index.html', ['Abstracts', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/Abstracts/index.html']
, ['Errors', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/Errors/index.html']
, ['Interfaces', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/Interfaces/index.html']
, ['Iterators', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/Iterators/index.html']
, ['XHTMLHeadersTemplates', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/index.html', ['XHTMLHeaderTemplate', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/index.html', ['Abstracts', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/Abstracts/index.html']
, ['Errors', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/Errors/index.html']
, ['Interfaces', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/Interfaces/index.html']
, ['Iterators', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/Iterators/index.html']
, ['XHTMLHeaderTemplate.php', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/XHTMLHeaderTemplate.php.html']
, ['loader.php', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/XHTMLHeaderTemplate/loader.php.html']
]
, ['loader.php', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplates/loader.php.html']
]
, ['XHTMLHeadersTemplate.php', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/XHTMLHeadersTemplate.php.html']
, ['loader.php', 'Templates/XHTMLTemplates/XHTMLHeadersTemplate/loader.php.html']
]
, ['XHTMLPageTemplate', 'Templates/XHTMLTemplates/XHTMLPageTemplate/index.html', ['Abstracts', 'Templates/XHTMLTemplates/XHTMLPageTemplate/Abstracts/index.html']
, ['Errors', 'Templates/XHTMLTemplates/XHTMLPageTemplate/Errors/index.html']
, ['Interfaces', 'Templates/XHTMLTemplates/XHTMLPageTemplate/Interfaces/index.html']
, ['Iterators', 'Templates/XHTMLTemplates/XHTMLPageTemplate/Iterators/index.html']
, ['XHTMLPageTemplate.php', 'Templates/XHTMLTemplates/XHTMLPageTemplate/XHTMLPageTemplate.php.html']
, ['loader.php', 'Templates/XHTMLTemplates/XHTMLPageTemplate/loader.php.html']
]
, ['XHTMLTemplate', 'Templates/XHTMLTemplates/XHTMLTemplate/index.html', ['Abstracts', 'Templates/XHTMLTemplates/XHTMLTemplate/Abstracts/index.html']
, ['Errors', 'Templates/XHTMLTemplates/XHTMLTemplate/Errors/index.html']
, ['Interfaces', 'Templates/XHTMLTemplates/XHTMLTemplate/Interfaces/index.html']
, ['Iterators', 'Templates/XHTMLTemplates/XHTMLTemplate/Iterators/index.html']
, ['XHTMLTemplate.php', 'Templates/XHTMLTemplates/XHTMLTemplate/XHTMLTemplate.php.html']
, ['loader.php', 'Templates/XHTMLTemplates/XHTMLTemplate/loader.php.html']
]
, ['loader.php', 'Templates/XHTMLTemplates/loader.php.html']
]
, ['loader.php', 'Templates/loader.php.html']
]
, ['loader.php', 'loader.php.html']
]
];
